# url: http://www.fireidea.com
name: 徐艺洲
description: 知止定静安虑得
encoding : utf-8

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# 你的博客logo图片URL，建议尺寸不超过300px × 300px
# avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
# favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /aboutme
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links:
  weibo: thinkpc
  facebook: xcl.rockman
  github: xcl3721
  rss: rss
  twitter: xcl3721

# 站点页脚的文字
footer-text: Copyright (c) 2019 thinkpc 京ICP备16019273号-1

# 评论，注意，请不要同时添加多种不同的评论区

# 输入Disqus shortname，即可添加评论区
disqus: fireidea #shortname


# 输入Google Analytics web tracking code
google_analytics: UA-27354989-1

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
# url: http://www.fireidea.com

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
# baseurl: /


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

